### PR TITLE
Oscar 1.1 compatibility

### PR DESCRIPTION
**Pull request by mvantellingen**
This also restructures the testing infrastructure: 
  - [x] Use pytest instead of nose
  - [x] Use factory-boy instead of django-dynamic-fixtures
  - [x] Implement bootstrap 3 templates
  - [x] Python 3 compat

### CODE REVIEW

**Comment by fghaas** [comment]
@codeinthehole, @maikhoepfel I'd be interested in Oscar 1.1 support for this module and have found this PR which has evidently been sitting here for several months now. Could someone please add a comment as to whether this is going in, or not?

**Comment by maikhoepfel** [comment]
Florian, @mvantellingen is an Oscar core contributor himself. My best guess is that he hasn't finished this PR, as there's items from the todo list missing. I'm sure he can chip in himself. I'm sure he's happy to receive some help.

As for me and David, we've dropped down to doing Oscar at a best-effort level, which I'm afraid is not a whole lot at the moment.

**Comment by fghaas** [comment]
Hmm, looking at the todo list and the commits it would seem like the PR adds merit even without the two still-open todo issues?

**Comment by fghaas** [comment]
Specifically, if I may say so, this is listed at https://github.com/django-oscar/django-oscar/blob/master/README.rst as an extension that is "stable and ready for use", which wouldn't really be true if this doesn't support Oscar 1.1 (which it currently seems not to). So anything that adds Oscar 1.1 support here would be a good thing, I guess. Or is the Bootstrap 3 bit a show stopper here?

**Comment by mvantellingen** [comment]
Hi, I'll be finishing this PR in approx two or three weeks since I'll need it myself for a client.

**Comment by fghaas** [comment]
OK thanks; I guess I'll check back in a couple of weeks then.

**Comment by fghaas** [comment]
Thanks @mvantellingen!

**Pull request merged**
