### PR TITLE
Fix Django 1.10 Compatability

### PR DESCRIPTION
**Pull request by crgwbr**

### CODE REVIEW

**Comment by mvantellingen** [comment]
Looks good, thanks! Only minor point is if we can keep a somewhat sane .gitignore file

**Comment by ahter** [comment]
Hi, when I try to install

    easy_install django-oscar-accounts
   
It gives the following error:

    error: Django 1.10.4 is installed but Django<1.10 is required by {'django-haystack'}

What can be done about this?

**Comment by crgwbr** [comment]
@ahter What version of haystack do you have?

**Comment by ahter** [comment]
@crgwbr 

    $ pip freeze   
    ...
    django-haystack==2.5.0

**Comment by crgwbr** [comment]
@ahter Upgrade to 2.5.1. It supports Django 1.10. See https://github.com/django-haystack/django-haystack/blob/v2.5.1/setup.py#L16.

**Comment by crgwbr** [comment]
@mvantellingen Ok, I removed the change to `.gitignore` since it's unrelated. What do you think our build matrix should be for this? I think at the least it makes sense to drop Django 1.8 since it's now unsupported. Even Django 1.9 is getting close to EOL.

**Comment by mvantellingen** [comment]
Perhaps we could standardise on a tox.ini file based on the one in django-oscar?  It should be extended for the oscar version. See https://github.com/django-oscar/django-oscar/blob/master/tox.ini


Django 1.8 is still supported since it is a LTS release. I know wagtail is keeping support for 1.8 but dropping 'official' support for 1.9. Maybe thats something we can also do, so Django 1.8 and Django 1.10 for now ?

**Comment by SalahAdDin** [comment]
Thank you!

**Comment by auvipy** [comment]
what about 1.11?

**Comment by solarissmoke** [comment]
#52

**Pull request closed without merging**
